#!/bin/sh
if [ $# -eq 0 ]
then
    echo "Usage: c-search [CONNPASS_EVENT_URL | CONNPASS_EVENT_ID]"
else
    id=`echo $1 | sed -e 's/[^0-9]//g'`
    curl -sL "connpass.com/api/v1/event/?event_id=${id}" | jq ".events[].series.id"
fi


