name: Brakeman Security Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  brakeman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Brakeman
        run: bundle exec brakeman --ignore-config config/brakeman.ignore --exit-on-warn --quiet
